version: '3.9'

services:
  frontend:
    image: ghcr.io/onino-io/blockscout-frontend:latest
    pull_policy: never
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/.env_frontend
